spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    database: mysql
    show-sql: off
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
  resources:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 80MB
